// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPynwqQ3WKfJdyQYBkv8HSonMc3oTSJq8',
    appId: '1:600866275869:web:55d326b4b5d6397a0dbcf4',
    messagingSenderId: '600866275869',
    projectId: 'snakegame-ef58a',
    authDomain: 'snakegame-ef58a.firebaseapp.com',
    storageBucket: 'snakegame-ef58a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaiCS2hWqqhSQ_30Miq4PxQ5Y8_bH-0qg',
    appId: '1:600866275869:android:423d3998ffa31a890dbcf4',
    messagingSenderId: '600866275869',
    projectId: 'snakegame-ef58a',
    storageBucket: 'snakegame-ef58a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs9HpEHGI93UMr8cz_8-4pyamywGdsRZU',
    appId: '1:600866275869:ios:b97575cb1b73bd160dbcf4',
    messagingSenderId: '600866275869',
    projectId: 'snakegame-ef58a',
    storageBucket: 'snakegame-ef58a.appspot.com',
    iosBundleId: 'com.example.snakeGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs9HpEHGI93UMr8cz_8-4pyamywGdsRZU',
    appId: '1:600866275869:ios:dc12794ff5a807fd0dbcf4',
    messagingSenderId: '600866275869',
    projectId: 'snakegame-ef58a',
    storageBucket: 'snakegame-ef58a.appspot.com',
    iosBundleId: 'com.example.snakeGame.RunnerTests',
  );
}
